// Typed access to data/brochures.json (generated by `npm run sync:brochures`).
import data from '@/data/brochures.json'

export type Brochure = (typeof data.projects)[number]

export const brochures: Brochure[] = data.projects
export const portfolioPdf: string = data.portfolioPdf

export const getBrochureBySlug = (slug: string) => brochures.find((b) => b.slug === slug)

export const fileName = (path: string) => path.split('/').pop() ?? path
